### ISSUE TITLE
Swipe Gesture

### ISSUE THREAD

**Issue by lmcgs** [nealyoung/NYSegmentedControl#13]
Swipe is not working well and there is no disable option.

**Comment by dimasv28** [comment]
Yeah, that will be great, if you will fix swipe bug...

**Comment by petergp** [comment]
If you are using head of the repo instead of the last tag, the problem should be fixed. You can do this with CocoaPods like this.

```
pod 'NYSegmentedControl', :git => 'git@github.com:nealyoung/NYSegmentedControl.git'
```

**Comment by nealyoung** [comment]
Should be fixed with the updated Podspec.
