### ISSUE TITLE
Update Podspec?

### ISSUE THREAD

**Issue by DoctorG** [nealyoung/NYSegmentedControl#17]
Can you integrate changes from krzyzanowskim/NYSegmentedControl and update podSpec please?  IBOutlet quite helpful

**Comment by DoctorG** [comment]
Are you still supporting this POD?

**Comment by DarthMike** [comment]
+1. Please update podspec. 

Thanks!

**Comment by nealyoung** [comment]
Podspec is updated, sorry for the delay.
