### ISSUE TITLE
Corner Radius issues

### ISSUE THREAD

**Issue by jimbojsb** [nealyoung/NYSegmentedControl#21]
My goal is to make a "square" segmented control. It seems like cornerRadius affects the corner radius of the control, but regardless what value I set that to, the selectedSegmentIndicator maintains a 4.0f corner radius. I see in the code where that is set but I don't see way to adjust it. Based on that, I also don't get how the examples are possible...

**Comment by jimbojsb** [comment]
After more fiddling, I see that -sizeToFit is what's required to make what I was expecting happen. Not sure if that is expected behavior, but if it is, feel free to close this issue.

**Comment by petergp** [comment]
The cornerRadius of the ```NYSegmentedControl``` is forwarded to ```selectedSegmentIndicator```. That is what makes the examples possible.

I think as for right now the expected behaviour is to call ```sizeToFit```, as it is done in the examples, however there is a PR that changes this need. #20
