### ISSUE TITLE
How to support chinese text?

### ISSUE THREAD

**Issue by xhzengAIB** [nealyoung/NYSegmentedControl#23]
The bug like this picture:

![bug](https://cloud.githubusercontent.com/assets/1969908/6962622/af6048f2-d968-11e4-911c-272e71d9294f.gif)

Jack

**Comment by xhzengAIB** [comment]
为什么？

**Comment by HiroshiHorie** [comment]
Same bug with Japanese

**Comment by nealyoung** [comment]
Thanks for the report, this issue should be fixed with [release 1.0.5](https://github.com/nealyoung/NYSegmentedControl/releases/tag/1.0.5) (also available on CocoaPods).
