### ISSUE TITLE
放入NavigationItem titleView中 不能使用中文

### ISSUE THREAD

**Issue by Eden2014** [nealyoung/NYSegmentedControl#24]
显示文字使用中文时出现BUG，1.3的版本中没有。

**Comment by HiroshiHorie** [comment]
Yes, Japanese Characters have a bug too...
![screencapture 2015-05-07 1 00 52](https://cloud.githubusercontent.com/assets/548776/7499912/92a11fdc-f454-11e4-9ea4-0dea7a45fa5c.png)

**Comment by nealyoung** [comment]
Thanks for the report, this issue should be fixed with [release 1.0.5](https://github.com/nealyoung/NYSegmentedControl/releases/tag/1.0.5) (also available on CocoaPods).
