### ISSUE TITLE
Strange thin line on the right side of selected indicator

### ISSUE THREAD

**Issue by hiroshihorie** [nealyoung/NYSegmentedControl#27]
I use the control in titleView, if i push and pop back it goes away but it appears anytime first time.
![screencapture 2015-05-25 2 52 27](https://cloud.githubusercontent.com/assets/548776/7789403/3715a3de-0289-11e5-935d-b7feecb84573.png)

**Comment by nealyoung** [comment]
Can you post the code you use to set up the control?

**Comment by colasjojo** [comment]
I have the same.

**Comment by colasjojo** [comment]
@nealyoung 
Hi, I have the same issue, and I found a way to fix it. But, it works only because I don't use the gradients.
I don't understand why it is so, but it works. It seems that overriding the `draw` method is the culprit.

In `NYSegmentIndicator.m`, you have this method

```obj-c
- (void)drawRect:(CGRect)rect {
    if (self.drawsGradientBackground) {
        CAGradientLayer *gradientLayer = (CAGradientLayer *)self.layer;
        gradientLayer.colors = @[(__bridge id)[self.gradientTopColor CGColor],
                                 (__bridge id)[self.gradientBottomColor CGColor]];
    } else {
        self.layer.backgroundColor = [self.backgroundColor CGColor];
    }
}
```

If you comment this method, there is no more this line.

**Comment by colasjojo** [comment]
@nealyoung 

I have new feed back on this.

I have the "strange" line with these settings

```obj-c
    [self.segmentedControl setUpForSegmentColor:color
                                     titleColor:[UIColor blackColor]
                             selectedTitleColor:[UIColor whiteColor]
                                           font:font
                                   cornerRadius:[CBDGlobalInfo cornerRadius]] ;
```

but it disappears when only changing `titleColor` to

```obj-c
    [self.segmentedControl setUpForSegmentColor:color
                                     titleColor:color
                             selectedTitleColor:[UIColor whiteColor]
                                           font:font
                                   cornerRadius:[CBDGlobalInfo cornerRadius]] ;
```

**Comment by colasjojo** [comment]
I have created a toy project that shows the problem.
It is only on the device, not on the simulator.

See: https://github.com/colasjojo/Test-NYSegmentedControl
