### ISSUE TITLE
Issue with the mask on the title

### ISSUE THREAD

**Issue by colasbd** [nealyoung/NYSegmentedControl#30]
When first loading the segmented control, the first text in the first selected segment is not properly rendered.

![capture d ecran 2015-08-19 a 14 53 00](https://cloud.githubusercontent.com/assets/4303814/9356581/09436bfc-4682-11e5-9a08-9d8bd5f203ee.png)
(first loading)

instead of 

![capture d ecran 2015-08-19 a 14 53 07](https://cloud.githubusercontent.com/assets/4303814/9356582/0e6660b2-4682-11e5-97d8-4324bd4db3ab.png)
(after selecting another segment and back to the first one)

Note: the first image corresponds to the label when one is moving ("panning") the segment from one index to another and when the titles are being masked interactively. If I stop my finger over a title, it will look like pic. 1 but when I release my finger and the segment becomes selected, then it looks like pic. 2.

So the issue is that when first appearing, the selected segment is as in pic. 1 and not as is pic. 2.

Thanks.

**Comment by colasjojo** [comment]
@nealyoung

I have created a toy project that shows the problem.
It is only on the device AND on the simulator.

See: https://github.com/colasjojo/Test-NYSegmentedControl

**Comment by neil-wu** [comment]
I have met the same problem now.  
The following is my code: (Swift)
```
        self.navSegControl = NYSegmentedControl(items: ["New", "Hot"])
        navSegControl.titleTextColor = UIColor.whiteColor()
        navSegControl.titleFont = UIFont.systemFontOfSize(12)
        navSegControl.selectedTitleTextColor = AppColor.TxtDeepGray
        navSegControl.selectedTitleFont = UIFont.systemFontOfSize(12)
        
        navSegControl.segmentIndicatorBackgroundColor = UIColor.whiteColor()
        navSegControl.backgroundColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.8)
        navSegControl.borderWidth = 0.0
        navSegControl.segmentIndicatorBorderWidth = 0.0
        navSegControl.segmentIndicatorInset = 2.0
        navSegControl.segmentIndicatorBorderColor = self.view.backgroundColor
        navSegControl.sizeToFit()
        navSegControl.cornerRadius = CGRectGetHeight(navSegControl.frame) / CGFloat(2.0)
        navSegControl.usesSpringAnimations = true
```

**Comment by neil-wu** [comment]
may be the problem is caused by the NYSegmentLabel.m 's drawRect.

**Comment by colasjojo** [comment]
@neil-wu the NYSegmentLabel.m 's `drawRect:` Yes.

But I have tried to create a `CALayer` and the result is the same...

**Comment by petergp** [comment]
I will take a look at it.

**Comment by petergp** [comment]
I rewrote how the `NYSegmentLabel` is being drawn. The problem should no longer exist. Can you guys let me know how it works for you before I make a PR.

I also included the fix in this issue #30, further it adds better support for changing font weight between normal and selected item.
```
pod 'NYSegmentedControl', :git => 'https://github.com/petergp/NYSegmentedControl.git', :branch => 'bugfix/selected-label
```

**Comment by neil-wu** [comment]
@petergp Hi，I tested in my project and also in @colasjojo 's  toy project, it seems that you have fix it.  :+1:

**Comment by petergp** [comment]
Great. I will wait for @colasjojo's feedback and then make a PR if everything is OK.

**Comment by colasjojo** [comment]
@petergp I'll come back to you in few hours. Thanks!

**Comment by colasjojo** [comment]
@petergp The https://github.com/nealyoung/NYSegmentedControl/issues/30#issuecomment-144047762 is fixed.

PS: The PR https://github.com/nealyoung/NYSegmentedControl/pull/34 is still to be included.

**Comment by petergp** [comment]
I have created PR #35 that fixes this. I am not a maintainer on this repo so we will have no rely on @nealyoung merging them.
