### ISSUE TITLE
crash when drag the segment button

### ISSUE THREAD

**Issue by zeptolee** [nealyoung/NYSegmentedControl#33]
the error info is:
Assertion failed: (CGFloatIsValid(x) && CGFloatIsValid(y)), function void CGPathMoveToPoint(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat), file Paths/CGPath.cc, line 254.

crash in this line:
 UIBezierPath *roundRectBezierPath = [UIBezierPath bezierPathWithRoundedRect:self.maskFrame
                                                                           cornerRadius:self.maskCornerRadius];

**Comment by nealyoung** [comment]
Are you using the latest version 1.0.7?

**Comment by zeptolee** [comment]
The 1.0.7 version has fixed this issue.
