### ISSUE TITLE
Issue when using clear background

### ISSUE THREAD

**Issue by gm6379** [nealyoung/NYSegmentedControl#38]
If I choose for the control to have a clear background, but set the selected segment indicator background to any color other than clear, when I select one of the other indexes, the selected segment indicator moves, but the background stays in place. See the attached screenshot.
![screen shot 2015-11-19 at 15 54 36](https://cloud.githubusercontent.com/assets/3264908/11275582/2c94bb28-8ed6-11e5-8c42-b81832e6fc3d.png)

**Comment by nealyoung** [comment]
I wasn't able to reproduce this issue, can you try the latest version (1.1.0) and check if this is still happening?

**Comment by nealyoung** [comment]
@gm6379 Closing this issue, please let me know if this is still valid.
