### ISSUE TITLE
Text Color issue when dragging

### ISSUE THREAD

**Issue by hugocroch** [nealyoung/NYSegmentedControl#41]
When you dragged the thumb to change section the second time, you will se see that the text ofthe current section stay the same color as selected
![exemple](https://cloud.githubusercontent.com/assets/6751906/12830549/dd8fdf84-cb5d-11e5-9484-289488453262.jpg)

The solution that I found without modify the library is to make layoutSubviews on the control after the "index changed" event.
Is there a way to fix it in the library instead to make it like I do?(Surely)

Thanks

**Comment by nealyoung** [comment]
I just pushed a new version (1.1.0) that changes how text drawing is handled and should solve this issue.
